// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://xufxxqyrsywafomryvam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1Znh4cXlyc3l3YWZvbXJ5dmFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MjkwODEsImV4cCI6MjA3MzQwNTA4MX0.y-gnuvl_84keOAvWu5PUyM1cNEkxGWHg81iC5GL7vSw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});